### ISSUE TITLE
Problem Identification: Stage 1

### ISSUE THREAD

**Issue by SujoodEldouma** [MIT-Emerging-Talent/2024-group-01-cdsp#1]
Let's brainstorm and come up with as many great ideas and questions as we want to work on, regardless of the constraints around the idea; just post it and let's have a discussion!

It's important to research and see if these questions have been answered/explored before.

> In the true spirit of design thinking, you start with a thorough discovery of problem or pain point, before you move on to the solution — in this case, the framework.

**Comment by hilaltech** [comment]
I love this part :)

Since I have a background in data analysis I have always thought about improving Agriculture in developing countries. Now let us just take the example of Afghanistan.  I must say that 58% of the land accounts for agriculture and farming but only 12 percent of this land is currently utilized. The remaining 48% lies fallow due to various factors, including the absence of scientific soil and climate analysis, and a lack of understanding of crop characteristics. Additionally, the irrigation schedule and system remain unanalyzed.

This situation isn't unique to Afghanistan but extends to many developing countries. I believe a comprehensive solution can address these common challenges. By integrating scientific soil and climate analysis, developing crops suited to specific conditions, and optimizing irrigation systems, we can unlock the untapped agricultural potential


So I pose the following question:

**1. How to improve agriculture in developing countries using Data Science ?**

**Comment by SujoodEldouma** [comment]
@hilaltech, that's a critical issue, tbh. Even in my country, Sudan, it's present, especially in this past decade, people have started migrating toward the centre where the capital city is located and have abandoned farming. A core issue related to this, I believe, is the length of the farming cycle "I am not sure if there's a more technical word for this xD", as you said we can work around soil data and weather data and develop a crop recommendation system, it can also have a market forecasting feature, because if we combine all these we can present them with the best crop to be planted based on the circumstances. 

I have some experience from my previous job; I worked on a project that used a similar model to analyze weather, soil, crop health and irrigation from geospatial photos of the pivots and other sensors planted around the pivot. We tried it in a couple of pivots and compared the results with the others that were traditionally monitored; it resulted in the optimization of water resources, Insecticides and the cycles themselves, and of course, it increased the profits by some large figure. 

> I love this part :)
> 
> Since I have a background in data analysis I have always thought about improving Agriculture in developing countries. Now let us just take the example of Afghanistan. I must say that 58% of the land accounts for agriculture and farming but only 12 percent of this land is currently utilized. The remaining 48% lies fallow due to various factors, including the absence of scientific soil and climate analysis, and a lack of understanding of crop characteristics. Additionally, the irrigation schedule and system remain unanalyzed.
> 
> This situation isn't unique to Afghanistan but extends to many developing countries. I believe a comprehensive solution can address these common challenges. By integrating scientific soil and climate analysis, developing crops suited to specific conditions, and optimizing irrigation systems, we can unlock the untapped agricultural potential
> 
> So I pose the following question:
> 
> **1. How to improve agriculture in developing countries using Data Science ?**

**Comment by SujoodEldouma** [comment]
Another pressing issue I propose in another domain - Education - is the immediate effect of wars and political situations on Educational Systems.
In developing countries, the educational systems are not just flawed; they are severely compromised by political conflicts that overcomplicate them and affect them at many levels. 
I witnessed this problem throughout the past year as the war erupted in Sudan. Regarding elementary/Secondary education, the academic year has started in some regions. Still, in others, it couldn't. As the schools were hosting displaced people, displaced populations faced more significant challenges, and they couldn't prioritize education. In addition to the unstable atmosphere that would affect the students mentally.
The situation was different and more complex for universities as most of them are located in the capital city - where the war is happening- and the academic year is postponed because there are no options. 

I suggest we do a predictive analysis and investigate the consequences and impact of these conflicts on the next generations.

**Comment by Lourdes148** [comment]
@hilaltech @SujoodEldouma 
It's an important issue. I am also an agronomist and have worked in this domain. My country faces almost similar problems, but it's more related to urbanization. Urbanization causes a significant loss of agricultural land in my country. 
However, in the education domain, I find Sujood's proposition very interesting. Haiti, my country, has been affected by gang wars since 2019. This has resulted in many displaced populations and a disinterest among young people and children in attending school. Also, I think a predictive analyze of this many wars in the World is very important.

**Comment by MiroMz** [comment]
Great start to the discussion and interesting ideas!

Climate, displacement, and inequality are all extremely important issues that are facing our humanity. Let me add my two cents of "problems":

Do you read/watch news? by how many media outlets?. do you cross-check the information that comes to you? 
I think we are living in an interesting time when it comes to information flows; the internet made the transaction of information as easy as it was never before, but with this advantage came many challenges like misinformation and cognitive overload to name a couple. and I believe that technology has the power to conquer this issue or a subset of it. I'm also very interested in NLP and if we choose to go in that direction I think we'll all have fun learning a very valuable aspect of CS

**Comment by SujoodEldouma** [comment]
Loving the conversation as well! There are too many interesting issues to start from.

@MiroMz I am also very interested in NLP and would love to explore it, but I have zero experience in this domain. 

One idea I was thinking about is how misinformation and falsified AI-generated news contribute to spreading hate speech or intensifying political conflicts. 
I think overall, I am interested in analysing the impact of political conflicts on different domains.

**Comment by Jossy9** [comment]
You guys have very interesting and relatable ideas. Even though I don't have much experience in this matter, I have some ideas.
To add to the conversation, I would like to turn the light on employability. We can talk about it so much here since I find it to be a common problem. Like, how is the employability rate increasing or decreasing? Are employers satisfied with the skills of their employees? How is the industrial-academy gap? How many employees are getting hired in the discipline they graduated with? Remote jobs vs. office jobs. How many times does it take for the average person to get a job after graduation? gender gaps, and many more issues related to employment.

**Comment by SujoodEldouma** [comment]
Updates;

We met as a team, discussed all the suggestions and decided to converge on two domains to do further research on and then finalize our problem identification.
The chosen domains:
- Media Analysis
- War/political conflicts impact on Education.
